name: GitHub Secrets

on:
  workflow_dispatch:

env: 
  App_Secret: ${{secrets.APP_SECRET}}

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:  
      - name: Print Secret
        run: |
            echo "APP_SECRET: ${{ env.App_Secret }}"
            echo "i_dont_exist: ${{ secrets.i_dont_exist  }}"
            
      - name: Print Secret as an environment variable
        run: |
            echo "APP_SECRET: $APP_SECRET"
        env:
            APP_SECRET: ${{ env.App_Secret }}